development:
  secret_key_base: 'e3c446c32d5f8de35da60ebbdafba46ef31d2c2365728a89f1d3008eacfa1e6f2b9ea6931a0c3a7dce44e40261b699e3c972b889fb361ab610c3aab6dfcf8adc'
  account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:

production:
  secret_key_base: 'your secret key base'
  account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>