# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
production_manager = Role.first_or_create(name: "Production Manager (PM)")
unit_production_manager = Role.first_or_create(name: "Unit Production Manager (UPM)")
key_pa = Role.first_or_create(name: "Key PA")
office_production_assistant = Role.first_or_create(name: "Office Production Assistant (OPA)")
location_manager = Role.first_or_create(name: "Location Manager (LM)")
assistant_location_manager = Role.first_or_create(name: "Assistant Location Manager (ALM)")
trainee_assistant_location_manager = Role.first_or_create(name: "Trainee Assistant Location Manager (TAL)")
first_assistant_director = Role.first_or_create(name: "1st Assistant Director (1st AD)")
second_assistant_director = Role.first_or_create(name: "2nd Assistant Director (2nd AD)")
third_assistant_director = Role.first_or_create(name: "3rd Assistant Director (3rd AD)")
trainee_assistant_director = Role.first_or_create(name: "Trainee Assistant Director (TAD)")
background_coordinator = Role.first_or_create(name: "Background Coordinator (AADBKC)")
director = Role.first_or_create(name: "Director")
producer = Role.first_or_create(name: "Producer")
director_assistant = Role.first_or_create(name: "Director’s Assistant")
producer_assistant = Role.first_or_create(name: "Producer’s Assistant")
art_production_design = Role.first_or_create(name: "Art / Production Design")
construction = Role.first_or_create(name: "Construction")
costumes = Role.first_or_create(name: "Costumes")
editors = Role.first_or_create(name: "Editors")
first_aid = Role.first_or_create(name: "First Aid / Craft Services (FACS)")
greens = Role.first_or_create(name: "Greens")
grips = Role.first_or_create(name: "Grips")
lighting = Role.first_or_create(name: "Lighting / Electrics (LX)")
hair = Role.first_or_create(name: "Hair")
make_up = Role.first_or_create(name: "Make Up")
paint = Role.first_or_create(name: "Paint")
production_coordinators = Role.first_or_create(name: "Production Coordinators")
properties= Role.first_or_create(name: "Properties (Props)")
script_supervisors = Role.first_or_create(name: "Script Supervisors")
set_dec = Role.first_or_create(name: "Set Dec")
sound = Role.first_or_create(name: "Sound")
special_effects = Role.first_or_create(name: "Special Effects (SPFX)")
transport = Role.first_or_create(name: "Transport")
visual_effects = Role.first_or_create(name: "Visual Effects")
location_scout = Role.first_or_create(name: "Location Scout")
stills_photographer = Role.first_or_create(name:"Stills Photographer")
