User.create!([
  {email: "ashley@gmail.com", encrypted_password: "$2a$10$.ZlcPrY7fJlmQCdiPvO.h.GliwpK1ROf0dSDHCfILQ8ODcuqZ5xka", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "ashley", photo: nil, phone: nil, is_dgc_member: false, has_traffic_control_ticket: false, has_vehicle: false, image: nil, admin: true, current_sign_in_at: "2017-04-14 23:26:21", last_sign_in_at: "2017-04-12 21:42:33", current_sign_in_ip: "10.0.2.2", last_sign_in_ip: "10.0.2.2", sign_in_count: 3, roles_ids: [], provider: nil, uid: nil, is_iatse_member: false, imdb: nil, youtube: nil, vimeo: nil, linkedin: nil, facebook: nil, notify_when_job_posted: "selected_roles"},
  {email: "smashley@gmail.com", encrypted_password: "$2a$10$bNvSjNyA4304grJr8SfCse0awTVLVAG/XgHmpsU5jnRCi4LmAd9ma", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "smashley", photo: nil, phone: nil, is_dgc_member: false, has_traffic_control_ticket: false, has_vehicle: false, image: nil, admin: nil, current_sign_in_at: "2017-04-15 00:32:37", last_sign_in_at: "2017-04-15 00:32:37", current_sign_in_ip: "10.0.2.2", last_sign_in_ip: "10.0.2.2", sign_in_count: 1, roles_ids: [], provider: nil, uid: nil, is_iatse_member: false, imdb: nil, youtube: nil, vimeo: nil, linkedin: nil, facebook: nil, notify_when_job_posted: "selected_roles"},
  {email: "noam.ascher@gmail.com", encrypted_password: "$2a$10$FRpYMd.lYCU5wBdfvhXDS.aOGWcW5kK9vm/ap/L8R0SHJhXhggrey", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "New User", photo: nil, phone: nil, is_dgc_member: false, has_traffic_control_ticket: false, has_vehicle: false, image: nil, admin: nil, current_sign_in_at: "2017-04-15 18:08:13", last_sign_in_at: "2017-04-15 18:08:13", current_sign_in_ip: "10.0.2.2", last_sign_in_ip: "10.0.2.2", sign_in_count: 1, roles_ids: [], provider: nil, uid: nil, is_iatse_member: false, imdb: nil, youtube: nil, vimeo: nil, linkedin: nil, facebook: nil, notify_when_job_posted: "selected_roles"},
  {email: "bashley@gmail.com", encrypted_password: "$2a$10$Fme4aezGN.DDu/HSONbk1.OdrmuTiBtBoC7opHWfex.7PC8c9tzmi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "bashley", photo: nil, phone: nil, is_dgc_member: false, has_traffic_control_ticket: false, has_vehicle: false, image: nil, admin: nil, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, sign_in_count: 0, roles_ids: [], provider: nil, uid: nil, is_iatse_member: false, imdb: nil, youtube: nil, vimeo: nil, linkedin: nil, facebook: nil, notify_when_job_posted: "selected_roles"},
  {email: "panacheley@gmail.com", encrypted_password: "$2a$10$u/avOqsV7m/kZEd8Sqn11ekztf6k28sxPKmMrSKZ5DpMKmdLx3wg.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, name: "panacheley", photo: nil, phone: nil, is_dgc_member: false, has_traffic_control_ticket: false, has_vehicle: false, image: nil, admin: nil, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, sign_in_count: 0, roles_ids: [], provider: nil, uid: nil, is_iatse_member: false, imdb: nil, youtube: nil, vimeo: nil, linkedin: nil, facebook: nil, notify_when_job_posted: "selected_roles"}
])
Appointment.create!([
  {user_id: 1, day: "4", week: "9 - 15", date: "2017-04-13"},
  {user_id: 1, day: "5", week: "23 - 29", date: "2017-04-28"},
  {user_id: 5, day: "2", week: "23 - 29", date: "2017-04-25"},
  {user_id: 5, day: "2", week: "16 - 22", date: "2017-04-18"},
  {user_id: 5, day: "4", week: "23 - 29", date: "2017-04-27"},
  {user_id: 5, day: "5", week: "16 - 22", date: "2017-04-21"}
])
Certificate.create!([
  {name: "WHMIS"},
  {name: "TCP"},
  {name: "TDG"},
  {name: "FORKLIFT TICKET"},
  {name: "AERIAL LIFT"},
  {name: "SCISSOR LIFT"},
  {name: "PAL GUN LICENSE"},
  {name: "ACT SAFE"},
  {name: "ELECTRICIAN TICKET"},
  {name: "LIFT TICKET"},
  {name: "SE DE EXAM"},
  {name: "BOOM LIFT TICKET"},
  {name: "FOODSAFE"},
  {name: "DRIVERS LICENSE CLASS 1"},
  {name: "DRIVERS LICENSE CLASS 2"},
  {name: "DRIVERS LICENSE CLASS 3"}
])
Eligibility.create!([
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 1},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 1},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 2},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 2},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 3},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 3},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 4},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 4},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 5},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 5},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 6},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 6},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 7},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 7},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 8},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 8},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 9},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 9},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 10},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 10},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 11},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 11},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 12},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 12},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 13},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 13},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 14},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 14},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 15},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 15},
  {member: nil, permit_days: nil, user_id: nil, union_id: 1, role_id: 16},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 16},
  {member: nil, permit_days: nil, user_id: nil, union_id: 4, role_id: 16},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 16},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 17},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 18},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 19},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 20},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 21},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 22},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 23},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 24},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 25},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 26},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 27},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 28},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 29},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 30},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 31},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 32},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 33},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 34},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 35},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 36},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 37},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 38},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 39},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 40},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 41},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 42},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 43},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 44},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 45},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 46},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 47},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 48},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 49},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 50},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 51},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 52},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 53},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 54},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 55},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 56},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 57},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 58},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 59},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 60},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 61},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 62},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 63},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 64},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 65},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 66},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 67},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 68},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 69},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 70},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 71},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 72},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 73},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 74},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 75},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 76},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 77},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 78},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 79},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 80},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 81},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 82},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 83},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 84},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 85},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 86},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 87},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 88},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 89},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 90},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 91},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 92},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 93},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 94},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 95},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 96},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 97},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 98},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 99},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 100},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 101},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 102},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 103},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 104},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 105},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 106},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 107},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 108},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 109},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 110},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 111},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 112},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 113},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 114},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 114},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 115},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 115},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 116},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 116},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 117},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 117},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 118},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 118},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 119},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 119},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 66},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 120},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 120},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 121},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 121},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 122},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 122},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 123},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 123},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 124},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 124},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 125},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 125},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 126},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 126},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 127},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 127},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 128},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 128},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 129},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 129},
  {member: nil, permit_days: nil, user_id: nil, union_id: 2, role_id: 130},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 130},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 131},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 132},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 133},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 134},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 135},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 136},
  {member: nil, permit_days: nil, user_id: nil, union_id: 3, role_id: 137},
  {member: nil, permit_days: nil, user_id: nil, union_id: 4, role_id: 137},
  {member: nil, permit_days: nil, user_id: nil, union_id: 4, role_id: 138},
  {member: nil, permit_days: nil, user_id: nil, union_id: 4, role_id: 139},
  {member: nil, permit_days: nil, user_id: nil, union_id: 4, role_id: 140},
  {member: nil, permit_days: nil, user_id: nil, union_id: 4, role_id: 141},
  {member: nil, permit_days: nil, user_id: nil, union_id: 5, role_id: 142},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 142},
  {member: nil, permit_days: nil, user_id: nil, union_id: 5, role_id: 143},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 143},
  {member: nil, permit_days: nil, user_id: nil, union_id: 5, role_id: 144},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 144},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 145},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 146},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 147},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 148},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 149},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 150},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 151},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 152},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 153},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 154},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 155},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 156},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 157},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 158},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 159},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 160},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 161},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 162},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 163},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 164},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 165},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 166},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 167},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 168},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 169},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 64},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 66},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 69},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 71},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 45},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 48},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 124},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 126},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 119},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 113},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 107},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 140},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 116},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 122},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 121},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 123},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 54},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 58},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 60},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 117},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 112},
  {member: nil, permit_days: nil, user_id: nil, union_id: 6, role_id: 115},
  {member: nil, permit_days: nil, user_id: 1, union_id: 2, role_id: 111},
  {member: nil, permit_days: nil, user_id: 1, union_id: 2, role_id: 36},
  {member: nil, permit_days: nil, user_id: 1, union_id: 1, role_id: 10},
  {member: nil, permit_days: nil, user_id: 1, union_id: 3, role_id: 123},
  {member: nil, permit_days: nil, user_id: 1, union_id: 3, role_id: 119},
  {member: nil, permit_days: nil, user_id: 5, union_id: 3, role_id: 133},
  {member: nil, permit_days: nil, user_id: 5, union_id: 3, role_id: 132}
])
Job.create!([
  {name: "buttonjob", description: "", starts_on: "2018-09-09", ends_on: nil, location: "Vancouver", contact_name: "smashley", contact_phone: "444-444-4444", contact_email: "smashley@gmail.com", company_name: "mgm", secret: "Cp_L0sGZ_ZXZC-XFSXii-w", published: true, role_id: 13, user_id: 3, job_filled: false}
])
Label.create!([
  {user_id: 1, job_id: nil, role_id: 111, job_board: nil, hiring_board: nil},
  {user_id: 1, job_id: nil, role_id: 36, job_board: nil, hiring_board: nil},
  {user_id: 1, job_id: nil, role_id: 10, job_board: nil, hiring_board: nil},
  {user_id: 1, job_id: nil, role_id: 123, job_board: nil, hiring_board: nil},
  {user_id: 1, job_id: nil, role_id: 119, job_board: nil, hiring_board: nil},
  {user_id: 3, job_id: "0c83f011-745b-4b5b-acc7-64a3a676bddc", role_id: 13, job_board: nil, hiring_board: nil},
  {user_id: 5, job_id: nil, role_id: 133, job_board: nil, hiring_board: nil},
  {user_id: 5, job_id: nil, role_id: 132, job_board: nil, hiring_board: nil}
])
Role.create!([
  {name: "Production Manager (PM)"},
  {name: "Key PA"},
  {name: "Office Production Assistant (OPA)"},
  {name: "Location Manager (LM)"},
  {name: "Assistant Location Manager (ALM)"},
  {name: "Trainee Assistant Location Manager (TAL)"},
  {name: "1st Assistant Director (1st AD)"},
  {name: "2nd Assistant Director (2nd AD)"},
  {name: "3rd Assistant Director (3rd AD)"},
  {name: "Trainee Assistant Director (TAD)"},
  {name: "BG Wrangler"},
  {name: "Producer’s Assistant"},
  {name: "Location Scout"},
  {name: "On Set Key"},
  {name: "On Set PA"},
  {name: "Transport"},
  {name: "Assistant Accountant"},
  {name: "Accounting Clerk 1"},
  {name: "Accounting Clerk 2"},
  {name: "Accounting Trainee"},
  {name: "Production Designer"},
  {name: "Art Director"},
  {name: "Assistant Art Director"},
  {name: "Draftsperson"},
  {name: "Graphics"},
  {name: "Illustrator"},
  {name: "Storyboard Artist"},
  {name: "Set Designer"},
  {name: "Art Department Assistant"},
  {name: "Construction Coordinator"},
  {name: "Construction Foreman"},
  {name: "Lead Carpenter"},
  {name: "Scenic Carpenter"},
  {name: "Metal Fabricator"},
  {name: "Scenic Metal Fabricator"},
  {name: "Construction Buyer"},
  {name: "Sculptor"},
  {name: "Model Maker"},
  {name: "Labourer (Construction)"},
  {name: "Costume Designer"},
  {name: "Asst. Costume Designer/Coordinator"},
  {name: "Set Supervisor"},
  {name: "Performer's Costumer"},
  {name: "Set Costumer"},
  {name: "Props Master"},
  {name: "Assistant Props Master"},
  {name: "Props"},
  {name: "Props Buyer"},
  {name: "Production Office Coordinator"},
  {name: "Assistant Production Office Coordinator"},
  {name: "2nd Assistant Office Coordinator"},
  {name: "Supervising Editor"},
  {name: "Supervising Sound Editor"},
  {name: "Editor"},
  {name: "Sound Effects Editor"},
  {name: "Music Editor"},
  {name: "Assistant Editor"},
  {name: "Sound Mixer"},
  {name: "Sound Boom"},
  {name: "Sound Assist"},
  {name: "Set Dec Buyer"},
  {name: "Set Dec Lead Dresser"},
  {name: "Set Dec On Set"},
  {name: "Key Grip"},
  {name: "Truck Grip"},
  {name: "Grip"},
  {name: "Dolly Grip"},
  {name: "Rigging Grip"},
  {name: "Gaffer"},
  {name: "Truck LX"},
  {name: "Lamp Op"},
  {name: "Rigging LX"},
  {name: "Hair Department Head"},
  {name: "Assistant Hairstylist"},
  {name: "Second Assistant Hairstylist"},
  {name: "Special Makeup Effects"},
  {name: "Makeup Department Head"},
  {name: "First Assistant Makeup Artist"},
  {name: "Second Assistant Makeup Artist"},
  {name: "Third Assistant Makeup Artist"},
  {name: "First Aid"},
  {name: "Craft Service"},
  {name: "Paint Coordinator"},
  {name: "Lead Painter"},
  {name: "Scenic Artist"},
  {name: "Sign Painter/Fabricator"},
  {name: "Scenic Painter"},
  {name: "Plasterer"},
  {name: "Set Painter"},
  {name: "Paint Labourer"},
  {name: "Script Supevisor/Continuity"},
  {name: "Assistant to Script Supervisor/Continuity"},
  {name: "Special Effects Coordinator"},
  {name: "First Assistant Special Effects"},
  {name: "Special Effects Assistant"},
  {name: "Special Effects Labourer"},
  {name: "VFX Artist ‐ Level 1"},
  {name: "VFX Artist ‐ Level 2"},
  {name: "VFX Artist ‐ Level 3"},
  {name: "VFX Technician ‐ Level 1"},
  {name: "VFX Technician ‐ Level 2"},
  {name: "Director of Photography"},
  {name: "Operator"},
  {name: "1st Assistant Operator"},
  {name: "2nd Assistant Operator"},
  {name: "Film Loader"},
  {name: "Trainee"},
  {name: "Motion Picture Video Coordinator"},
  {name: "Motion Picture Video Assistant 1"},
  {name: "Motion Picture Video Assistant 2"},
  {name: "Digital Imaging Technician"},
  {name: "Visual Effects"},
  {name: "Paint"},
  {name: "Art / Production Design"},
  {name: "Construction"},
  {name: "Costumes"},
  {name: "First Aid / Craft Services (FACS)"},
  {name: "Head Greensperson"},
  {name: "Greensperson"},
  {name: "Lighting / Electrics (LX)"},
  {name: "Hair"},
  {name: "Make Up"},
  {name: "Accountant"},
  {name: "Properties (Props)"},
  {name: "Script Supervisors"},
  {name: "Set Decorator"},
  {name: "Sound"},
  {name: "Special Effects (SPFX)"},
  {name: "Office"},
  {name: "Production"},
  {name: "Catering"},
  {name: "Animals"},
  {name: "Wrangler"},
  {name: "Scenic Art"},
  {name: "Publicity"},
  {name: "Prop Building"},
  {name: "Security"},
  {name: "Captain"},
  {name: "Co-Captain"},
  {name: "Driver"},
  {name: "Picture Car"},
  {name: "Actor"},
  {name: "Stand In"},
  {name: "Extra"},
  {name: "Unit Production Manager (UPM)"},
  {name: "Background Coordinator (AADBKC)"},
  {name: "Director"},
  {name: "Producer"},
  {name: "Director’s Assistant"},
  {name: "Stills Photographer"},
  {name: "Casting Director"},
  {name: "Background Casting"},
  {name: "Properties Master"},
  {name: "Visual FX Animator"},
  {name: "Visual FX Compositor"},
  {name: "Visual FX Artist"},
  {name: "Production Coordinator"},
  {name: "Gennie Op"},
  {name: "Designer"},
  {name: "Camera Operator"},
  {name: "1st Camera Assist"},
  {name: "2nd Camera Assist"},
  {name: "DIT"},
  {name: "Scripty"},
  {name: "Transport Captain"},
  {name: "Special Effects Make Up"},
  {name: "Assistant Production Coordinator"},
  {name: "Sound Editor"},
  {name: "Boom Op"}
])
Union.create!([
  {name: "DGC", has_member_status: false, has_permit_status: false},
  {name: "IATSE", has_member_status: false, has_permit_status: false},
  {name: "ACFC", has_member_status: false, has_permit_status: false},
  {name: "TEAMSTERS", has_member_status: false, has_permit_status: false},
  {name: "UBCP/ACTRA", has_member_status: false, has_permit_status: false},
  {name: "None", has_member_status: false, has_permit_status: false}
])
