# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
production_manager = Role.create(name: "Production Manager (PM)")
unit_production_manager = Role.create(name: "Unit Production Manager (UPM)")
key_pa = Role.create(name: "Key PA")
office_production_assistant = Role.create(name: "Office Production Assistant (OPA)")
location_manager = Role.create(name: "Location Manager (LM)")
assistant_location_manager = Role.create(name: "Assistant Location Manager (ALM)")
trainee_assistant_location_manager = Role.create(name: "Trainee Assistant Location Manager (TAL)")
first_assistant_director = Role.create(name: "1st Assistant Director (1st AD)")
second_assistant_director = Role.create(name: "2nd Assistant Director (2nd AD)")
third_assistant_director = Role.create(name: "3rd Assistant Director (3rd AD)")
trainee_assistant_director = Role.create(name: "Trainee Assistant Director (TAD)")
background_coordinator = Role.create(name: "Background Coordinator (AADBKC)")
director = Role.create(name: "Director")
producer = Role.create(name: "Producer")
director_assistant = Role.create(name: "Director’s Assistant")
producer_assistant = Role.create(name: "Producer’s Assistant")
art_production_design = Role.create(name: "Art / Production Design")
construction = Role.create(name: "Construction")
costumes = Role.create(name: "Costumes")
editors = Role.create(name: "Editors")
first_aid = Role.create(name: "First Aid / Craft Services (FACS)")
greens = Role.create(name: "Greens")
grips = Role.create(name: "Grips")
lighting = Role.create(name: "Lighting / Electrics (LX)")
hair = Role.create(name: "Hair")
make_up = Role.create(name: "Make Up")
paint = Role.create(name: "Paint")
production_coordinators = Role.create(name: "Production Coordinators")
properties= Role.create(name: "Properties (Props)")
script_supervisors = Role.create(name: "Script Supervisors")
set_dec = Role.create(name: "Set Dec")
sound = Role.create(name: "Sound")
special_effects = Role.create(name: "Special Effects (SPFX)")
transport = Role.create(name: "Transport")
visual_effects = Role.create(name: "Visual Effects")
location_scout = Role.create(name: "Location Scout")
stills_photographer = Role.create(name:"Stills Photographer")

#comment out previous data to avoid duplication

casting_director = Role.create(name: "Casting Director")
background_casting = Role.create(name: "Background Casting")
accountant = Role.create(name: "Accountant")
properties_master = Role.create(name: "Properties Master")
visual_FX_animators = Role.create(name: "Visual FX Animators")
visual_FX_compositors = Role.create(name: "Visual FX Compositors")
visual_FX_artists = Role.create(name: "Visual FX Artists")

dgc = Union.create(name: "DGC")
iatse_891 = Union.create(name: "IATSE 891")
iatse_669 = Union.create(name: "IATSE 669")
acfc= Union.create(name: "ACFC")
teamsters = Union.create(name: "TEAMSTERS")
none= Union.create(name: "None")


on_set_key= Role.create(name: "On Set Key")
catering= Role.create(name: "Catering")
actor= Role.create(name:"Actor")
stand_in= Role.create(name:"Stand In")
extra= Role.create(name:"Extra")
security= Role.create(name:"Security")
animals= Role.create(name:"Animals")
wranglers = Role.create(name:"Wranglers")
scenic_art = Role.create(name:"Scenic Art")
publicity= Role.create(name: "Publicity")
prop_buidling = Role.create(name: "Prop Building")
office= Role.create(name:"Office")
production = Role.create(name: "Production")

whmis=Certificate.create(name: "WHMIS")
tcp=Certificate.create(name: "TCP")
tdg=Certificate.create(name: "TDG")
forklift_ticket=Certificate.create(name: "FORKLIFT TICKET")
aerial_lift = Certificate.create(name:"AERIAL LIFT")
scissor_lift= Certificate.create(name:"SCISSOR LIFT")
pal_gun_license= Certificate.create(name:"PAL GUN LICENSE")
act_safe= Certificate.create(name: "ACT SAFE")
electricians_ticket = Certificate.create(name:"ELECTRICIAN TICKET")
life_ticket= Certificate.create(name: "LIFT TICKET")
se_de_exam= Certificate.create(name:"SE DE EXAM")
boom_lift_ticket= Certificate.create(name:"BOOM LIFT TICKET")
food_safe= Certificate.create(name:"FOODSAFE")
drivers_license_class_one= Certificate.create(name:"DRIVERS LICENSE CLASS 1")
drivers_license_class_two= Certificate.create(name:"DRIVERS LICENSE CLASS 2")
drivers_license_class_three= Certificate.create(name:"DRIVERS LICENSE CLASS 3")

